name: Demo workflow

on:
  workflow_dispatch:
#  workflow_run:
#    workflows: [ "Merge to demo" ]
#    types:
#      - completed
#

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Build something nice.
        run: echo "Bob the Builder"
      - name: Go rest 10 sec.
        run: sleep 10
      - name: Work is done, go home
        run: sleep 10

